version: "3.9"
services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configuration/prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./configuration/grafana/provisioning:/etc/grafana/provisioning/
      - ./data/grafana/db:/var/lib/grafana
    env_file:
      - ./configuration/grafana/grafana.env
    depends_on:
      - prometheus
