version: "3.9"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
    - ./configuration/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana/db:/var/lib/grafana
      - ./data/grafana/provisioning/:/etc/grafana/provisioning/

